CREATE DATABASE CEMLAD;

USE CEMLAD;

CREATE TABLE CAREER(
	ID_CAREER INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CAREER VARCHAR(100) NOT NULL,
	PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE USER(
	ID_USER INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_CAREER INT(4) NOT NULL,
	USER VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD VARCHAR(32) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	SECOND_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50) NOT NULL,
	SECOND_LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(70) NOT NULL,
	PHONE VARCHAR(13) NOT NULL,
	ALTER_PHONE VARCHAR(13),
	ROL VARCHAR(8) NOT NULL,
	FOREIGN KEY (ID_CAREER) REFERENCES CAREER(ID_CAREER)
);

CREATE TABLE QUESTION(
	ID_QUESTION INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	QUESTION VARCHAR(200) NOT NULL
);

CREATE TABLE TEST(
	ID_TEST INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_USER INT(4) NOT NULL,
	ID_QUESTION INT(4) NOT NULL,
	ANSWER VARCHAR(200) NOT NULL,
	VALUE INT(4) NOT NULL,
	FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER),
	FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION(ID_QUESTION)
);

CREATE TABLE OFFER(
	ID_OFFER INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_CAREER INT(4) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PRICE DECIMAL(10, 2) NOT NULL,
	FOREIGN KEY (ID_CAREER) REFERENCES CAREER(ID_CAREER)
);

CREATE TABLE FILES(
	ID_FILE INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_USER INT(4) NOT NULL,
	NAME VARCHAR(75) NOT NULL,
	DIR VARCHAR(75) NOT NULL,
	TYPE VARCHAR(8) NOT NULL,
	FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER)
);
